# Generated by Django 5.2.7 on 2026-10-03 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payguard', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cardattempt',
            new_name='payguard_ca_user_id_0cdd89_idx',
            old_name='payguard_ca_user_id_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='cardattempt',
            new_name='payguard_ca_fingerp_160e29_idx',
            old_name='payguard_ca_fingerp_7a8b9c_idx',
        ),
        migrations.RenameIndex(
            model_name='cardcooldown',
            new_name='payguard_ca_kind_28ebb7_idx',
            old_name='payguard_ca_kind_1a2b3c_idx',
        ),
    ]
