# Generated by Django 5.2.7 on 2026-10-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payguard', '0002_rename_payguard_ca_user_id_4d5e6f_idx_payguard_ca_user_id_0cdd89_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcooldown',
            name='permanent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='cardcooldown',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
